### PR TITLE
DAOS-6794 build: Include patch for daos API change

### PR DESCRIPTION
**Pull request by mjean308**
Signed-off-by: Maureen Jean <maureen.jean@intel.com>

### CODE REVIEW

**Review by mchaarawi — CHANGES_REQUESTED** [review]
we shouldn't be doing this.
this change should be committed upstream not patched in here.

**Comment by brianjmurrell** [comment]
> we shouldn't be doing this.
> this change should be committed upstream not patched in here.

I would only add that locally patching (i.e. temporarily) is only acceptable once the patch has been pushed upstream and accepted, as a means to get the functionality locally before upstream creates a release with the patch in it.  Unless we are resigned to maintaining a fork, which I do not believe is the case for this repo.

**Comment by mjean308** [comment]
The PR was created so that the daos change could be tested with the patch.    Should we just close the PR and once the change has been landed upstream another PR can create the rpms with the correct tags/commit of the change?

**Comment by GitHuaKuang** [comment]
Tried to push the related change PR to vol-daos, failed, does it need to subscribe to it?

[boro-59:/home/huakuang/vol-daos]$ git commit -sa
Error detected while processing /home/huakuang/.vimrc:
line   40:
E538: No mouse support: mouse=r
Press ENTER or type command to continue
[daos-6794 c19858e] Change to coordinate with daos-6794 Remove pool APIs from src/include/daos_mgmt.h
 1 file changed, 11 insertions(+), 3 deletions(-)
[boro-59:/home/huakuang/vol-daos]$ git push origin daos-6794
Username for 'https://github.com': GitHuaKuang
Password for 'https://GitHuaKuang@github.com':
remote: Permission to HDFGroup/vol-daos.git denied to GitHuaKuang.
fatal: unable to access 'https://github.com/HDFGroup/vol-daos.git/': The requested URL returned error: 403

**Comment by brianjmurrell** [comment]
> The PR was created so that the daos change could be tested with the patch.

If you mean that this PR is just testing the patch before it is submitted upstream, that is another valid use case I would think.

> Should we just close the PR and once the change has been landed upstream another PR can create the rpms with the correct tags/commit of the change?

Well, not really.  In fact only including the patch in an RPM build for a stable upstream package is actually the more proper method of building RPMs.  For stable upstreams, we really shouldn't be pulling random commits as what we build.

So this PR is fine (a) to test the patch in order to send upstream (assuming it stays a PR) and (b) to land, but only if/when upstream accepts the patch and lands it to their branch, or (c) if we are going to take on ownership (and the SDL burden) of maintaining a fork.  I don't think (c) is the case here, but just being clear about the possible cases.

**Comment by brianjmurrell** [comment]
> Tried to push the related change PR to vol-daos, failed, does it need to subscribe to it?
> ...
> remote: Permission to HDFGroup/vol-daos.git denied to GitHuaKuang.
> fatal: unable to access 'https://github.com/HDFGroup/vol-daos.git/': The requested URL returned error: 403

I don't think this PR is really the forum for this sort of thing (so further discussion can probably be elsewhere) @GitHuaKuang, but you seem to be trying to push to `https://github.com/HDFGroup/vol-daos.git`.  Have HDFGroup given you permission to push to their repo?  Don't you more likely want to push a PR to them for them to review and land?

**Comment by GitHuaKuang** [comment]
> > Tried to push the related change PR to vol-daos, failed, does it need to subscribe to it?
> > ...
> > remote: Permission to HDFGroup/vol-daos.git denied to GitHuaKuang.
> > fatal: unable to access 'https://github.com/HDFGroup/vol-daos.git/': The requested URL returned error: 403
> 
> I don't think this PR is really the forum for this sort of thing (so further discussion can probably be elsewhere) @GitHuaKuang, but you seem to be trying to push to `https://github.com/HDFGroup/vol-daos.git`. Have HDFGroup given you permission to push to their repo? Don't you more likely want to push a PR to them for them to review and land?

Yes, that is the purpose - to land this PR to vol-daos. I used to send patch to Ray who owns vol-daos, somehow I got frim @mchaarawi message sounds like we should push the PR by ourselves. @mchaarawi please provide details of how to push PR to vol-daos?

**Comment by mchaarawi** [comment]
> Tried to push the related change PR to vol-daos, failed, does it need to subscribe to it?
> 
> [boro-59:/home/huakuang/vol-daos]$ git commit -sa
> Error detected while processing /home/huakuang/.vimrc:
> line 40:
> E538: No mouse support: mouse=r
> Press ENTER or type command to continue
> [daos-6794 c19858e] Change to coordinate with daos-6794 Remove pool APIs from src/include/daos_mgmt.h
> 1 file changed, 11 insertions(+), 3 deletions(-)
> [boro-59:/home/huakuang/vol-daos]$ git push origin daos-6794
> Username for 'https://github.com': GitHuaKuang
> Password for 'https://GitHuaKuang@github.com':
> remote: Permission to HDFGroup/vol-daos.git denied to GitHuaKuang.
> fatal: unable to access 'https://github.com/HDFGroup/vol-daos.git/': The requested URL returned error: 403

you (and me) are not allowed to push to that repo. this is not owned by our org. you need to create a PR to the master branch. you can create a fork on your account, push a branch there and then create a PR with that.

**Comment by mchaarawi** [comment]
> > Tried to push the related change PR to vol-daos, failed, does it need to subscribe to it?
> > [boro-59:/home/huakuang/vol-daos]$ git commit -sa
> > Error detected while processing /home/huakuang/.vimrc:
> > line 40:
> > E538: No mouse support: mouse=r
> > Press ENTER or type command to continue
> > [daos-6794 c19858e] Change to coordinate with daos-6794 Remove pool APIs from src/include/daos_mgmt.h
> > 1 file changed, 11 insertions(+), 3 deletions(-)
> > [boro-59:/home/huakuang/vol-daos]$ git push origin daos-6794
> > Username for 'https://github.com': GitHuaKuang
> > Password for 'https://GitHuaKuang@github.com':
> > remote: Permission to HDFGroup/vol-daos.git denied to GitHuaKuang.
> > fatal: unable to access 'https://github.com/HDFGroup/vol-daos.git/': The requested URL returned error: 403
> 
> you (and me) are not allowed to push to that repo. this is not owned by our org. you need to create a PR to the master branch. you can create a fork on your account, push a branch there and then create a PR with that.

alternatively, you can send the patch to Jerome Soumagne <jsoumagne@hdfgroup.org> and CC me.
but i can tell you this would take longer to integrate.

**Pull request closed without merging**
