### PR TITLE
DAOS-6794 build: Update vol-test to 1.1.0rc3

### PR DESCRIPTION
**Pull request by cibervicho**
Signed-off-by: David Maldonado Moreno <david.maldonado.moreno@intel.com>

### CODE REVIEW

**Review by berserk-fury — DISMISSED** [review]

**Review by brianjmurrell — COMMENTED** [review]
rc2 to rc3 is really so big/different that rc2 didn't need boost but rc3 does?

**Comment by cibervicho** [comment]
> rc2 to rc3 is really so big/different that rc2 didn't need boost but rc3 does?

I had to add boost because when compiling I was getting errors like this:

[2021-04-01T16:12:35.910Z] [ 74%] Building C object test/vol/CMakeFiles/h5_test_testhdf5.dir/hdf5_test/ttime.c.o
[2021-04-01T16:12:35.910Z] In file included from /builddir/build/BUILD/vol-daos-1.1.0rc3/src/daos_vol.h:24:0,
[2021-04-01T16:12:35.910Z]                  from /builddir/build/BUILD/vol-daos-1.1.0rc3/src/daos_vol_file.c:16:
[2021-04-01T16:12:35.910Z] /usr/include/cart/api.h:31:34: fatal error: boost/preprocessor.hpp: No such file or directory
[2021-04-01T16:12:35.910Z]  #include <boost/preprocessor.hpp>
[2021-04-01T16:12:35.910Z]                                   ^
[2021-04-01T16:12:35.910Z] compilation terminated.

**Comment by brianjmurrell** [comment]
> I had to add boost because when compiling I was getting errors like this:
> 
> [2021-04-01T16:12:35.910Z] [ 74%] Building C object test/vol/CMakeFiles/h5_test_testhdf5.dir/hdf5_test/ttime.c.o
> [2021-04-01T16:12:35.910Z] In file included from /builddir/build/BUILD/vol-daos-1.1.0rc3/src/daos_vol.h:24:0,
> [2021-04-01T16:12:35.910Z] from /builddir/build/BUILD/vol-daos-1.1.0rc3/src/daos_vol_file.c:16:
> [2021-04-01T16:12:35.910Z] /usr/include/cart/api.h:31:34: fatal error: boost/preprocessor.hpp: No such file or directory
> [2021-04-01T16:12:35.910Z] #include <boost/preprocessor.hpp>

It seems like this is a bug upstream and they shouldn't be using `cart/api.h`.  Rather than propagating that bug into the packaging here (that will likely also get left over once they fix that upstream), it would be better to get this fixed upstream and then apply the patch that they commit to remove this usage, which also removes the need for the `BuildRequires: boost-devel` here.

**Review by brianjmurrell — CHANGES_REQUESTED** [review]
Let's get upstream fixed so that we don't need to add boost now.

**Comment by mchaarawi** [comment]
> > I had to add boost because when compiling I was getting errors like this:
> > [2021-04-01T16:12:35.910Z] [ 74%] Building C object test/vol/CMakeFiles/h5_test_testhdf5.dir/hdf5_test/ttime.c.o
> > [2021-04-01T16:12:35.910Z] In file included from /builddir/build/BUILD/vol-daos-1.1.0rc3/src/daos_vol.h:24:0,
> > [2021-04-01T16:12:35.910Z] from /builddir/build/BUILD/vol-daos-1.1.0rc3/src/daos_vol_file.c:16:
> > [2021-04-01T16:12:35.910Z] /usr/include/cart/api.h:31:34: fatal error: boost/preprocessor.hpp: No such file or directory
> > [2021-04-01T16:12:35.910Z] #include <boost/preprocessor.hpp>
> 
> It seems like this is a bug upstream and they shouldn't be using `cart/api.h`. Rather than propagating that bug into the packaging here (that will likely also get left over once they fix that upstream), it would be better to get this fixed upstream and then apply the patch that they commit to remove this usage, which also removes the need for the `BuildRequires: boost-devel` here.

i think for now it's fine to move on with this and we can remove that once the usage of cart/api.h is removed upstream (can create a ticket to track this).
i don't see this as a bug, even if it's not necessary to use this header, as we install that header in include/ today.

**Review by mchaarawi — APPROVED** [review]

**Comment by brianjmurrell** [comment]
> i think for now it's fine to move on with this and we can remove that once the usage of cart/api.h is removed upstream (can create a ticket to track this).

While I can appreciate the theory of this, how (and by whom) does this ticket ever actually get actioned once upstream has removed the `cart/api.h` usage?  IOW, what prevents this ticket from just lingering on and on in Jira forever since it's waiting on an external action to be completed to become actionable?  I suppose if whoever opens the ticket upstream at HDFGroup/vol-daos owns our ticket to remove the `Build-Requires: boost-devel`, they will be able to do that once upstream closes the ticket we open with them.  I'd be fine with that process.  Getting the upstream ticket and our ticket to fix this once upstream has fixed it put into a comment in this PR would be good so that there is a reference to close out the conversation.

> i don't see this as a bug, even if it's not necessary to use this header, as we install that header in include/ today.

Ultimately (at least until this is fixed) we are installing a dependency that is unnecessary.  boost-devel was removed from the daos.spec in daos-stack/daos@723e311dbdefac04831c7c09b52927bdafe8fcc5 in DAOS-6819 specifically because we were installing more dependencies on user's machines than were actually necessary.  That seems to be the case here also.

Will it be difficult to get upstream to fix this?  As soon as they commit the fix to remove it, we can simply add that patch to this PR and achieve our desired goal now rather than down the road.  But that can follow the ticket process above.

**Review by brianjmurrell — DISMISSED** [review]

**Comment by mchaarawi** [comment]
just FYI https://github.com/HDFGroup/vol-daos/pull/22 was landed to remove the cart header

**Comment by brianjmurrell** [comment]
> just FYI [HDFGroup/vol-daos#22](https://github.com/HDFGroup/vol-daos/pull/22) was landed to remove the cart header

Indeed.  I saw that too.  Thanks for the head's up though.

@cibervicho Can you pull the patch for that and add it to this PR as a `Patch0:` in the specfile (you'll need to add a corresponding `%patch0` to the `%setup`)?  That should allow you to remove the boost-devel BR.

**Comment by cibervicho** [comment]
> > just FYI [HDFGroup/vol-daos#22](https://github.com/HDFGroup/vol-daos/pull/22) was landed to remove the cart header
> 
> Indeed. I saw that too. Thanks for the head's up though.
> 
> @cibervicho Can you pull the patch for that and add it to this PR as a `Patch0:` in the specfile (you'll need to add a corresponding `%patch0` to the `%setup`)? That should allow you to remove the boost-devel BR.

Done. All checks passed. Should I restart CI in the other PR?

**Review by berserk-fury — APPROVED** [review]

**Comment by cibervicho** [comment]
PR passed

**Review by brianjmurrell — APPROVED** [review]

**Comment by brianjmurrell** [comment]
This actually failed on landing: https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fhdf5-vol-daos/detail/master/21/pipeline.

Given that that means that a new hdf5-vold-daos was not created and we have been using the one before this landing in our CI, I am inclined to just revert this and somebody else can have another go at it.

**Pull request merged**
